//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.288.
// 
using System.Xml.Serialization;

namespace PSL.TotalRecall.PolicyManager 
{

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psl.cs.columbia.edu/discus2/Not")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://psl.cs.columbia.edu/discus2/Not", IsNullable=false)]
	public class Not 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement Any;
	}

}