//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.288.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psl.cs.columbia.edu/discus2/RequiresParticipants")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://psl.cs.columbia.edu/discus2/RequiresParticipants", IsNullable=false)]
public class RequiresParticipants {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Participant")]
    public string[] Participant;
}
